import { axios, localhost } from '../other/utils/axios/axios'


export const createCategory = (data) => axios.postData(`${localhost}/deletefood`, data)
export const editCategory = (id, data) => axios.putData(`${localhost}/editCategory/${id}`, data)
export const deleteCategory = (id) => axios.delete(`${localhost}/deleteCategory/${id}`)
export const createChildItem = (id, data) => axios.postData(`${localhost}/createChildItem/${id}`, data)
export const editChildItem = (id, data) => axios.putData(`${localhost}/editChildItem/${id}`, data)
export const deleteChildItem = (id) => axios.delete(`${localhost}/deleteChildItem/${id}`)
export const listUnAvailable = () => axios.get(`${localhost}/listUnAvailable`)
export const changeAvailable = (data) => axios.post(`${localhost}/changeAvailable/${id}`, data)
export const createNotification = (data) => axios.post(`${localhost}/createNotification`, data)
export const deleteNotification = () => axios.delete(`${localhost}/deleteNotification`)
export const setAdmin = (data) => axios.post(`${localhost}/setAdmin`, data)
export const deleteAdmin = (phoneOrEmail) => axios.delete(`${localhost}/deleteAdmin?phoneOrEmail=${phoneOrEmail}`)
export const getAllAdmin = () => axios.get(`${localhost}/getAllAdmin`)
export const changeMainAdmin = (data) => axios.put(`${localhost}/changeMainAdmin`, data)
export const getProposal = () => axios.get(`${localhost}/getProposal`)
export const deleteMultiProposal = (data) => axios.delete(`${localhost}/deleteMultiProposal`, data)
export const getAllAddress = () => axios.get(`${localhost}/getAllAddress`)
export const deleteAddressForOneAdmin = (id) => axios.delete(`${localhost}/deleteAddressForOneAdmin/${id}`)
export const deleteAllAddress = () => axios.delete(`${localhost}/deleteAllAddress`)
export const sendDisablePost = (data) => axios.post(`${localhost}/sendDisablePost`, data)
export const sendPostPrice = (data) => axios.post(`${localhost}/sendPostPrice`, data)
export const getPostPrice = () => axios.get(`${localhost}/getPostPrice`)
export const getAllUser = () => axios.get(`${localhost}/getAllUser`)
export const adminTicketBox = () => axios.get(`${localhost}/adminTicketBox`)
export const getSocketIoSeen = () => axios.get(`${localhost}/getSocketIoSeen`)
