import { axios, localhost } from '../other/utils/axios/axios'


export const getSlider = async () => axios.get(`${localhost}/getSlider`)
export const getCategory = async () => axios.get(`${localhost}/getCategory`)
export const getChildItems = async (id) => axios.get(`${localhost}/getChildItems/${id}`)
export const getSingleItem = async (id) => axios.get(`${localhost}/getSingleItem/${id}`)
export const getOffers = async () => axios.get(`${localhost}/getOffers`)
export const getSimilars = async (id) => axios.get(`${localhost}/getSimilars/${id}`)
export const getPopulars = async () => axios.get(`${localhost}/getPopulars`)
export const createComment = async (id, data) => axios.post(`${localhost}/createComment/${id}`, data)
export const getChildItemComments = async (id) => axios.get(`${localhost}/getChildItemComments/${id}`)
export const editComment = async (id, commentid, data) => axios.put(`${localhost}/editComment/${id}?commentid=${commentid}`, data)
export const deleteComment = async (id) => axios.delete(`${localhost}/deleteComment/${id}`)
export const getSingleComment = async (id) => axios.get(`${localhost}/getSingleComment/${id}`)
export const getNotification = async () => axios.get(`${localhost}/getNotification`)
export const reverse = async (data) => axios.post(`${localhost}/reverse`, data)
export const geocode = async (data) => axios.post(`${localhost}/geocode`, data)
export const confirmPayment = async (data) => axios.post(`${localhost}/confirmPayment`, data)
export const commentLike = async (id) => axios.post(`${localhost}/commentLike/${id}`)
export const commentDisLike = async (id) => axios.post(`${localhost}/commentDisLike/${id}`)
